### ISSUE TITLE
Running action to obtain udids crashes on macos runner

### ISSUE THREAD

**Issue by r-dev-limited** [firebase/fastlane-plugin-firebase_app_distribution#362]
`app/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-plugin-firebase_app_distribution-0.8.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_udids.rb:31:in `run': undefined method `empty?' for nil:NilClass (NoMethodError)`

```
  lane :download_udids do
    firebase_app_distribution_get_udids(
        app: ENV["FIREBASE_APP_ID_IOS"],
        output_file: tester_udids_file,
        debug:true
    )
  end

  lane :add_new_devices do
    register_devices(
      devices_file: tester_udids_file,
      api_key_path: "itunes_key.json",
    )
  end
```

Service account is populated with previous action step:
```
 - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.gcp_service_account }}"
          create_credentials_file: true
          export_environment_variables: true
```

Fastlane is called by:
```
 - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.0"
          bundler-cache: true
          working-directory: 'app/ios'

  - uses: maierj/fastlane-action@v3.0.0
        with:
          lane: "install_certs"
          subdirectory: "app/ios"
```

I tried same solution also with self-hoster runner and macos runner which fails the same.
Error indicates something weird in uuid property in rb code
